openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Water Tracker App
tags:
  - name: Auth
    description: Auth operations
  - name: User
    description: Operations with User data
  - name: Water
    description: Water consumption tracking operations
servers:
  - url: https://project-group-05-backend.onrender.com
  - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signup.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /user/current:
    get:
      $ref: ../swagger/paths/user/current.yaml
  /user/update:
    patch:
      $ref: ../swagger/paths/user/update.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/addWater.yaml
  /water/today/{date}:
    get:
      $ref: ../swagger/paths/water/getWaterByDay.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      required:
        - email
        - password
      properties:
        _id:
          description: 'Backend-generated unique identifier.'
          type: string
          example: '679e59ee76bc89b649731a32'
        name:
          description: 'User`s name. Should be at most 32 characters'
          type: string
          example: 'John Doe'
        email:
          description: 'User`s email. Is required. Should be in format example@mail.com'
          type: string
          example: 'example@mail.com'
        password:
          description: 'User`s password. Is required. Should be at least 8 and at most 64 characters'
          type: string
          example: '123456asd'
        gender:
          description: 'User`s gender. Should be one of the suggested values'
          type: string
          enum: ['female', 'male']
          example: 'female'
        dailyNorm:
          description: 'User`s daily norm of water. Should be at most 15000 ml. Default value is 1500 ml'
          type: number
          example: 1500
        avatar:
          description: 'User`s avatar'
          type: string
          example: 'https://res.cloudinary.com/dtfo6b7gi/image/upload/v1738226311/tzsd56ad…'
    Water:
      type: object
      required:
        - date
        - userId
        - entries
      properties:
        date:
          description: 'Recording date in format YYYY-MM-DD'
          type: string
          example: '2024-02-01'
        userId:
          description: 'The ID of the User who created the entry'
          type: string
          example: '65af5c7e8d3f3b1f2e3a7c9a'
        entries:
          description: 'Array of records about water consumption'
          type: array
          items:
            type: object
            required:
              - time
              - waterVolume
            properties:
              time:
                description: 'Water consumption time in format YYYY-MM-DDTHH:MM'
                type: string
                example: '2024-02-01T08:30'
              waterVolume:
                description: 'Volume of water drunk in milliliters'
                type: number
                example: 250
