openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Water Tracker App
tags:
  - name: Auth
    description: Auth operations
  - name: User
    description: Operations with User`s data
  - name: Water
    description: Water consumption tracking operations
servers:
  - url: https://project-group-05-backend.onrender.com
  # - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signup.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /user:
    patch:
      $ref: ../swagger/paths/user/updateUser.yaml
  /user/current:
    get:
      $ref: ../swagger/paths/user/currentUser.yaml
  /user/avatar:
    patch:
      $ref: ../swagger/paths/user/updateAvatar.yaml
  /user/water-rate:
    patch:
      $ref: ../swagger/paths/user/updateWaterRate.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/addWater.yaml
  /water/day/{date}:
    get:
      $ref: ../swagger/paths/water/getWaterByDay.yaml
  /water/month/{yearMonth}:
    get:
      $ref: ../swagger/paths/water/getWaterByMonth.yaml
  /water/{entryId}:
    patch:
      $ref: ../swagger/paths/water/updateWater.yaml
    delete:
      $ref: ../swagger/paths/water/deleteWater.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    user:
      $ref: ../swagger/components/schemas/user.yaml
    water:
      $ref: ../swagger/components/schemas/water.yaml
