openapi: 3.1.0
info:
  version: 1.0.0
  title: Water Tracker App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Water Tracker App
tags:
  - name: Auth
    description: Auth operations
  - name: User
    description: Operations with User data
  - name: Water
    description: Water consumption tracking operations
servers:
  - url: https://project-group-05-backend.onrender.com
  - url: http://localhost:3000
paths:
  /auth/signup:
    post:
      $ref: ../swagger/paths/auth/signup.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /user/current:
    get:
      $ref: ../swagger/paths/user/currentUser.yaml
  /user/update:
    patch:
      $ref: ../swagger/paths/user/updateUser.yaml
  /user/update-water-rate:
    patch:
      $ref: ../swagger/paths/user/updateWaterRate.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/addWater.yaml
  /water/today/{date}:
    get:
      $ref: ../swagger/paths/water/getWaterByDay.yaml
  /water/{year}/{month}:
    get:
      $ref: ../swagger/paths/water/getWaterByMonth.yaml
  /water/{entryId}:
    patch:
      $ref: ../swagger/paths/water/updateWater.yaml
    delete:
      $ref: ../swagger/paths/water/deleteWater.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      required:
        - email
        - password
      properties:
        _id:
          description: 'Backend-generated unique identifier.'
          type: string
          example: '67a210a28f7f42ba355eb221'
        name:
          description: 'User`s name. Should be at most 32 characters'
          type: string
          example: 'Lady Gaga'
        email:
          description: 'User`s email. Is required. Should be in format example@mail.com.'
          type: string
          example: 'ladygaga@mail.com'
        password:
          description: 'User`s password. Is required. Should be at least 8 and at most 64 characters.'
          type: string
          example: '1234567890'
        gender:
          description: 'User`s gender. Should be one of the suggested values.'
          type: string
          enum: ['female', 'male']
          example: 'female'
        dailyNorm:
          description: 'User`s daily norm of water. Should be at most 15000 ml. Default value is 2000 ml.'
          type: number
          example: 2000
        avatar:
          description: 'User`s avatar'
          type: string
          example: 'https://res.cloudinary.com/dhfwc4nmz/image/upload/v1738667492/ysf70wtw63hihtf14spo.avif'
    Water:
      type: object
      required:
        - date
        - userId
        - entries
      properties:
        date:
          description: 'Recording date in format YYYY-MM-DD.'
          type: string
          example: '2024-02-04'
        userId:
          description: 'The ID of the User who created the entry.'
          type: string
          example: '67a210a28f7f42ba355eb221'
        entries:
          description: 'Array of records about water consumption, consists of time in format YYYY-MM-DDTHH:mm and waterVolume.'
          type: array
          items:
            type: object
            required:
              - time
              - waterVolume
            properties:
              time:
                description: 'Water consumption time in format YYYY-MM-DDTHH:mm.'
                type: string
                example: '2024-02-04T15:30'
              waterVolume:
                description: 'Volume of water drunk in milliliters.'
                type: number
                example: 250
